### ISSUE TITLE
load .py files from current folder fails

### ISSUE THREAD

**Issue by prjemian** [sstoupin/dtxrd#1]
on 2016-07-28, Stan emailed me:

If you remember, to let dtxrd see .py modules in a current folder, you suggested:

```
user_dir = os.getcwd()
sys.path.append(user_dir)
sys.path.pop()
```

This works with the debian package
but it doesn't seem to work if installed using
python setup.py install  or with dtxrd on anaconda

one still has to include the current folder to PYTHONPATH

If you have any ideas on how to fix it please let me know.

**Comment by prjemian** [comment]
@sstoupin:  the `sys.path.append(user_dir)` code is in `seehdf` and it expects to find a file `ccd.py`.  Where is that file?  I can _fake_ that file for testing that the import technique will work.

**Comment by prjemian** [comment]
'''
    ccd.py: dummy local file
    '''

    # values from file: seehdf
    rbin=1
    dx, dy = 1.0, 1.0  # CCD camera pixel size [mm]
    tot_range=10000.0	  # upper limit for threshold processing (to exclude "dead" pixels)
    dyn_range=10000.0	   # upper limit for threshold processing (gauss)
    fwhm_0=30.0        # expected fwhm (for fitting)
    bkg0=2750.0        # "reasonable" background - dark current count
    # default paths in hdf or h5 file
    data_path='/entry/instrument/detector/data'
    th_path='/entry/instrument/detector/NDAttributes/theta'
    chi_path='/entry/instrument/detector/NDAttributes/chi'

**Comment by sstoupin** [comment]
Pete,

Thanks for your quick response.

for testing seehdf please go to

/home/beams/S1BMUSER/data/2016-2/Antipov_RCTOPO_07JUN16/CVD111-1_front

an appropriate ccd.py is in the folder

to test seehdf just run

seehdf -s -i CVD111-2_f-1__150.h5

it will raise an error message if unable to find ccd.py

Thanks!

Stan

**Comment by prjemian** [comment]
Worked for me.  Perhaps our accounts behave differently...

```
jemian@gov .../Antipov_RCTOPO_07JUN16/CVD111-1_front $ which seehdf
/home/oxygen/JEMIAN/Apps/anaconda/bin/seehdf
jemian@gov .../Antipov_RCTOPO_07JUN16/CVD111-1_front $ seehdf -s -i CVD111-2_f-1__150.h5
# seehdf 0.16 by Stanislav Stoupin <sstoupin@gmail.com>
nx =  1024
ny =  1024
# filename: CVD111-2_f-1__150.h5
# image: 1024 x 1024
angle [orig. units]  = 457.83334542
chi [orig. units] = 2.79994
jemian@gov .../Antipov_RCTOPO_07JUN16/CVD111-1_front $
```

and a nice 2-D image appeared from matplotlib

**Comment by sstoupin** [comment]
If I login to our beamline computer "topo" as "s1bmuser"

then go to that folder and run same commands

which seehdf
/APSshare/anaconda/x86_64/bin/seehdf

seehdf -s -i CVD111-2_f-1__150.h5
Traceback (most recent call last):
   File "/APSshare/anaconda/x86_64/bin/seehdf", line 168, in <module>
     main(options, args)
   File "/APSshare/anaconda/x86_64/bin/seehdf", line 102, in main
     from ccd import rbin,dx,dy,tot_range,dyn_range,fwhm_0,bkg0
ImportError: No module named ccd

Don't know why

Stan

**Comment by prjemian** [comment]
http://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path#67692

**Comment by prjemian** [comment]
You got that message because the version of dtxrd seen from host topo is still the old one.
The update from the master DSERV to the sector DSERVs happend overnight between 2 and 7 am.

**Comment by prjemian** [comment]
I don't have the s1bmuser password so ran the new version (from my development directory) using a different beamline account.  The new version is successful:

```
user@host ~ $ cd /home/beams/S1BMUSER/data/2016-2/Antipov_RCTOPO_07JUN16/CVD111-1_front
user@host /tmp $ python /home/oxygen/JEMIAN/Documents/eclipse/dtxrd/seehdf -s -i CVD111-2_f-1__150.h5 
# seehdf 0.16 by Stanislav Stoupin <sstoupin@gmail.com>
nx =  1024
ny =  1024
# filename: CVD111-2_f-1__150.h5
# image: 1024 x 1024
angle [orig. units]  = 457.83334542
chi [orig. units] = 2.79994
user@host /tmp $ 
```

and a plot window appears

(comment was revised since this also worked in the original directory)

**Comment by sstoupin** [comment]
Thanks!
I will test again with the new version
I thought the old version already had
user_dir = os.getcwd()
sys.path.append(user_dir)
sys.path.pop()

... will let you know

Stan

**Comment by prjemian** [comment]
installed version tested OK for me from another beamline host:

```
user@host ~ $ cd /home/beams/S1BMUSER/data/2016-2/Antipov_RCTOPO_07JUN16/CVD111-1_front
user@host .../Antipov_RCTOPO_07JUN16/CVD111-1_front $ which seehdf
/APSshare/anaconda/x86_64/bin/seehdf
user@host .../Antipov_RCTOPO_07JUN16/CVD111-1_front $ seehdf -s -i CVD111-2_f-1__150.h5
# seehdf 0.16 by Stanislav Stoupin <sstoupin@gmail.com>
nx =  1024
ny =  1024
# filename: CVD111-2_f-1__150.h5
# image: 1024 x 1024
angle [orig. units]  = 457.83334542
chi [orig. units] = 2.79994
```

If you agree, we can close this issue on GitHub

**Comment by sstoupin** [comment]
Yes. I just tried and it also works for s1bmuser@topo
The issue can be closed.

Thanks!

Stan
